version: '3.0'
services:
  dash:
    image: stabya45/car_price_prediction:v0.1
    build: 
      context: .
      dockerfile: car.DockerFile
    volumes:
      - ./.vscode-server:/root/.vscode-server
      - ./sourceCode:/root/sourceCode
    ports:
      - 9999:8050
      

